### ISSUE TITLE
populate chart for missing days

### ISSUE THREAD

**Issue by kra** [breedx2/futel-usage-viz#17]
currently, missing days don't populate the X
if they did I could make custom charts by preprocessing the metrics files

one easy way to test them is to look at Q1 2019 which has no data

**Comment by breedx2** [comment]
Which view are you referring to?  There's definitely code in place to pad missing dates in both the OpenSignal view and the "by date" view (note Q1 2019 as you pointed out):
![image](https://user-images.githubusercontent.com/1888255/101307983-9c17ef80-37fd-11eb-9a87-20a2723a5894.png)

**Comment by breedx2** [comment]
I have merged changes from #18 into gh-pages, so please refresh and close if there is no more to do on this or comment about what's left.  :metal:

**Comment by breedx2** [comment]
@kra are we happy that there are not missing days now?  Can we close this plz?
