### ISSUE TITLE
enable rewriting of types

### ISSUE THREAD

**Issue by kra** [breedx2/futel-usage-viz#2]
the naming format is not consistent on the server like foo_bar, foo-bar, foo-bar-ivr, foo-bar-context, and never will be

normalization will get most of the wey, like -> "foo bar"
but we may need a map from metric name to prose name

**Comment by breedx2** [comment]
The PR that closes this exposes a json file for name mappings (also noted in the readme).  If you want something fancier, please open a new issue with details about that fancy thing.  :v:
