### ISSUE TITLE
document how to make a pdf of a chart

### ISSUE THREAD

**Issue by kra** [breedx2/futel-usage-viz#23]
is this just the q&d solution?
print webpage to pdf and then then cut and paste the relevant rectangle out with an image editor such as g*mp?

**Comment by breedx2** [comment]
https://github.com/breedx2/futel-usage-viz#saving-graphs--making-a-pdf

Shouldn't require any image editing or screenshotting or printing...so I made a note in the readme.  Reopen if you wanna do more with this.
