### ISSUE TITLE
can't save a view with a subset of names

### ISSUE THREAD

**Issue by kra** [breedx2/futel-usage-viz#35]
problem: I want to be able to easily see several saved views, for example "only incoming and outgoing main directories" "operator and operator-nopickup" "ring-*" etc

my attempt at a q&d solution is to save good-metric-names.json which seems to be what the readme is telling me to do. So, for example, I save good-metrics-names.json as

```
[
"hold_the_phone_main",
"incoming-ivr",
"outgoing-ivr",
"outgoing-ivr-detroit",
"outgoing-ivr-souwester",
"outgoing-ivr-ypsi",
"outgoing_portland_menu",
"outgoing_souwester_menu",
]
```

and restart the server by ^c and re-run npm run server

I visit "by month" and click the gear, I see all names in the select box. I select all and see a graph of all names. I want to see only the names in good-metric-names.json

**Comment by breedx2** [comment]
the `good-metric-names.json` that the readme is talking about is for filtering during preprocessing.  You have to run `npm run preprocess` if you want to pick up the changes. If you only ever want the above listed event types, then this is reasonable...but lots of other potentially interesting things will have been excluded from ALL of the preprocessed output.

Do you think that maybe handling this as "predefined views" is maybe a better approach?  Like, there's a button or whatever and you click it and then a selection of predefined events is chosen automatically?  Does that do what you're looking for?

**Comment by kra** [comment]
OK, that works, thanks.

I can make json files with human readable names and copy them to good-metric-names.json before rendering, that will let me save images to include with other content and lets me set up sets beforehand.

It would be good for the user to be able to select these subsets like we do the open signal ones, though.

**Comment by kra** [comment]
I think the solution for now is "implement a selectable preset" and work from there
