### ISSUE TITLE
update outgoing-ivr preset

### ISSUE THREAD

**Issue by kra** [breedx2/futel-usage-viz#38]
["hold_the_phone_main",
"incoming-ivr",
"outgoing-ivr",
"outgoing-ivr-detroit",
"outgoing-ivr-souwester",
"outgoing-ivr-ypsi",
"outgoing_portland_menu",
"outgoing_souwester_menu"]

**Comment by breedx2** [comment]
Happy to make this change, but it's definitely odd/confusing that "outgoing-ivr" would contain something called "incoming-ivr".  Is there maybe a more descriptive preset -- like "main ivr menu" or "root content" or something?

**Comment by breedx2** [comment]
Also did you overlook `outgoing_detroit_menu` or was that excluded intentionally?
