### ISSUE TITLE
Move existing charts to pre-munged data

### ISSUE THREAD

**Issue by breedx2** [breedx2/futel-usage-viz#9]
The existing charts in the UI feed off of a single month of raw data only.  It's not scalable...and we have a way to preprocess the data now, so let's migrate the existing charts to those next.  This effort will also help to clarify #7

**Comment by kra** [comment]
maybe we should just not include the data and instead include scripts for user to use to normalize to avoid mistakes and leaks

if we just want to let people get started the open signal data post-munging is probably safe enough to use as an example
